### ISSUE TITLE
Merge api data

### ISSUE THREAD

**Issue by DenisLopatin** [francis-schiavo/blizzard_api_php#1]
Hi. The blizzard api has a question about merging data when it is received from the api. Let's say we need to get a list of leaders (pvp), we will need to make a number of more requests to merge data, among them a request to get pictures, get character data separately, and so on (I don't remember, I've been working for a long time, but I think you understand what I'm getting at).

Do you think such a thing should be provided in an open source library, for example, this one, or is it already the responsibility of a specific application, and such libraries should be as simple as possible?

**Comment by francis-schiavo** [comment]
This library is the PHP equivalent of my main Ruby library that I wrote just to see if I still have some PHP skills. So it was designed to fetch each endpoint in a separate call.

I think the data required by each app may vary. While I think it could be wrapped in a library, it should be highly customizable so it will be useful for a lot of scenarios.

Perhaps some wrapper to receive multiple endpoint URIs and fetch them asynchronously (possibly using curl_multi_exec), waiting for the responses and joining them into an array/object before returning. I think that would be the most PHP way of doing such merging of data.

**Comment by francis-schiavo** [comment]
I helped writing a similar library a few years ago and at some point we addressed this issue by having a **bulk_execute** method.
The project seems abandoned now, but you can probably use that as a reference: https://gitlab.com/davidmatthew/blizzard-api-php/-/blame/master/blizzard_api/request_handler.php#L271
